import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Ablaze Vulnerabilities DB",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="flex justify-between fixed top-0 left-0 w-full h-16 bg-white/75 backdrop-blur-xl border-b border-gray-200 z-9999">
                    <div className="flex items-center ml-8 font-bold text-lg">
                        <a href="/">Ablaze Vulnerabilities DB</a>
                    </div>
                    <div className="flex items-center font-mono text-sm">
                        <a className="flex items-center gap-2 mr-8 hover:underline hover:underline-offset-4" href="/about">
                            About
                        </a>
                    </div>
                </div>
                <div className="mt-26 mx-8">{children}</div>
            </body>
        </html>
    );
}
